{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 82,
   "source": [
    "# auto reload notebook deps\n",
    "%reload_ext autoreload\n",
    "%autoreload 2"
   ],
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n",
      "[autoreload of utils.dataset failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/anaconda3/envs/spec-project/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/anton164/git/fall-spec/utils/dataset.py\", line 1, in <module>\n",
      "    from utils import flatten\n",
      "ImportError: cannot import name 'flatten' from 'utils' (unknown location)\n",
      "]\n"
     ]
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "source": [
    "import json\n",
    "import pandas as pd\n",
    "\n",
    "DATASETS = {\n",
    "    \"CentralParkNYC\": {\n",
    "        \"input_location\": \"./data/tweet_objects/CentralParkNYC/2021-01-27-2021-02-06.json\",\n",
    "        \"output_location\": \"./data/mstream_datasets/CentralParkNYC-2021-01-27-2021-02-06.json\",\n",
    "        \"spike_start\": \"Feb 1, 2021, 17:00\",\n",
    "        \"spike_end\": \"Feb 3, 2021, 04:00\",\n",
    "    },\n",
    "    \"united\": {\n",
    "        \"input_location\": \"./data/tweet_objects/united/2020-12-05-2020-12-15.json\",\n",
    "        \"output_location\": \"./data/mstream_datasets/united-2020-12-05-2020-12-15.json\",\n",
    "        \"spike_start\": \"Dec 12, 2020, 05:00\",\n",
    "        \"spike_end\": \"Dec 13, 2020, 06:00\",\n",
    "    },\n",
    "    \"nationalGridUS\": {\n",
    "        \"input_location\": \"./data/tweet_objects/nationalGridUS/2020-10-01-2020-10-12.json\",\n",
    "        \"output_location\": \"./data/mstream_datasets/nationalGridUS-2020-10-01-2020-10-12.json\",\n",
    "        \"spike_start\": \"Oct 7, 2020, 17:00\",\n",
    "        \"spike_end\": \"Oct 9, 2020, 04:00\",\n",
    "    }\n",
    "}\n",
    "\n",
    "selected_dataset = DATASETS[\"nationalGridUS\"]\n",
    "labeled_spike_start = pd.to_datetime(selected_dataset[\"spike_start\"]).tz_localize(\"UTC\")\n",
    "labeled_spike_end = pd.to_datetime(selected_dataset[\"spike_end\"]).tz_localize(\"UTC\")"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "source": [
    "from utils.dataset import create_tweet_df\n",
    "\n",
    "with open(selected_dataset[\"input_location\"], \"r\") as f:\n",
    "    raw_dataset = json.load(f)\n",
    "\n",
    "df_tweets = create_tweet_df(raw_dataset[\"tweets\"])\n",
    "\n",
    "# Label tweets\n",
    "df_tweets[\"is_anomaly\"] = df_tweets.created_at.apply(\n",
    "    lambda x: 0 if (x < labeled_spike_start or x > labeled_spike_end) else 1\n",
    ")\n",
    "\n",
    "df_tweets.head()"
   ],
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>text</th>\n",
       "      <th>created_at</th>\n",
       "      <th>hashtags</th>\n",
       "      <th>mentions</th>\n",
       "      <th>in_reply_to_user_id</th>\n",
       "      <th>user_id</th>\n",
       "      <th>retweet_count</th>\n",
       "      <th>quote_count</th>\n",
       "      <th>reply_count</th>\n",
       "      <th>like_count</th>\n",
       "      <th>retweeted</th>\n",
       "      <th>replied_to</th>\n",
       "      <th>quoted</th>\n",
       "      <th>is_anomaly</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2125</th>\n",
       "      <td>1311464085071036416</td>\n",
       "      <td>@nationalgridus YESS!!! It’s back on</td>\n",
       "      <td>2020-10-01 00:32:58+00:00</td>\n",
       "      <td>[]</td>\n",
       "      <td>[nationalgridus]</td>\n",
       "      <td>109524559</td>\n",
       "      <td>812872943134982144</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1311416336787091457</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2124</th>\n",
       "      <td>1311464351459672065</td>\n",
       "      <td>@ToSaveEnergy @SCE @LimeEnergy @NYPAenergy @na...</td>\n",
       "      <td>2020-10-01 00:34:01+00:00</td>\n",
       "      <td>[Maintenance, cooling, energyefficiency, refri...</td>\n",
       "      <td>[ToSaveEnergy, SCE, LimeEnergy, NYPAenergy, na...</td>\n",
       "      <td>17881345</td>\n",
       "      <td>1591198093</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1311369549837676544</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2123</th>\n",
       "      <td>1311464409559166976</td>\n",
       "      <td>RT @ToSaveEnergy: Another insightful #ActiveEf...</td>\n",
       "      <td>2020-10-01 00:34:15+00:00</td>\n",
       "      <td>[ActiveEfficiency]</td>\n",
       "      <td>[ToSaveEnergy]</td>\n",
       "      <td>None</td>\n",
       "      <td>1591198093</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1311369549837676544</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2122</th>\n",
       "      <td>1311469381868814337</td>\n",
       "      <td>@DeanFelicetti Hi Dean. We understand not havi...</td>\n",
       "      <td>2020-10-01 00:54:01+00:00</td>\n",
       "      <td>[]</td>\n",
       "      <td>[DeanFelicetti]</td>\n",
       "      <td>3225669874</td>\n",
       "      <td>109524559</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1311404424661737477</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2121</th>\n",
       "      <td>1311471757967134722</td>\n",
       "      <td>@DeanFelicetti @nationalgridus Didn’t the wind...</td>\n",
       "      <td>2020-10-01 01:03:27+00:00</td>\n",
       "      <td>[]</td>\n",
       "      <td>[DeanFelicetti, nationalgridus]</td>\n",
       "      <td>3225669874</td>\n",
       "      <td>170846420</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1311404424661737477</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                       id                                               text  \\\n",
       "2125  1311464085071036416               @nationalgridus YESS!!! It’s back on   \n",
       "2124  1311464351459672065  @ToSaveEnergy @SCE @LimeEnergy @NYPAenergy @na...   \n",
       "2123  1311464409559166976  RT @ToSaveEnergy: Another insightful #ActiveEf...   \n",
       "2122  1311469381868814337  @DeanFelicetti Hi Dean. We understand not havi...   \n",
       "2121  1311471757967134722  @DeanFelicetti @nationalgridus Didn’t the wind...   \n",
       "\n",
       "                    created_at  \\\n",
       "2125 2020-10-01 00:32:58+00:00   \n",
       "2124 2020-10-01 00:34:01+00:00   \n",
       "2123 2020-10-01 00:34:15+00:00   \n",
       "2122 2020-10-01 00:54:01+00:00   \n",
       "2121 2020-10-01 01:03:27+00:00   \n",
       "\n",
       "                                               hashtags  \\\n",
       "2125                                                 []   \n",
       "2124  [Maintenance, cooling, energyefficiency, refri...   \n",
       "2123                                 [ActiveEfficiency]   \n",
       "2122                                                 []   \n",
       "2121                                                 []   \n",
       "\n",
       "                                               mentions in_reply_to_user_id  \\\n",
       "2125                                   [nationalgridus]           109524559   \n",
       "2124  [ToSaveEnergy, SCE, LimeEnergy, NYPAenergy, na...            17881345   \n",
       "2123                                     [ToSaveEnergy]                None   \n",
       "2122                                    [DeanFelicetti]          3225669874   \n",
       "2121                    [DeanFelicetti, nationalgridus]          3225669874   \n",
       "\n",
       "                 user_id  retweet_count  quote_count  reply_count  like_count  \\\n",
       "2125  812872943134982144              0            0            0           0   \n",
       "2124          1591198093              0            0            0           0   \n",
       "2123          1591198093              3            0            0           0   \n",
       "2122           109524559              0            0            0           0   \n",
       "2121           170846420              0            0            0           0   \n",
       "\n",
       "                retweeted           replied_to quoted  is_anomaly  \n",
       "2125                  NaN  1311416336787091457    NaN           0  \n",
       "2124                  NaN  1311369549837676544    NaN           0  \n",
       "2123  1311369549837676544                  NaN    NaN           0  \n",
       "2122                  NaN  1311404424661737477    NaN           0  \n",
       "2121                  NaN  1311404424661737477    NaN           0  "
      ]
     },
     "metadata": {},
     "execution_count": 84
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "source": [
    "# Export \n",
    "df_tweets.to_json(\n",
    "    selected_dataset[\"output_location\"],\n",
    "    orient=\"records\"\n",
    ")"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "source": [
    "df_tweets.info()"
   ],
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 2126 entries, 2125 to 0\n",
      "Data columns (total 15 columns):\n",
      " #   Column               Non-Null Count  Dtype              \n",
      "---  ------               --------------  -----              \n",
      " 0   id                   2126 non-null   object             \n",
      " 1   text                 2126 non-null   object             \n",
      " 2   created_at           2126 non-null   datetime64[ns, UTC]\n",
      " 3   hashtags             2126 non-null   object             \n",
      " 4   mentions             2126 non-null   object             \n",
      " 5   in_reply_to_user_id  1302 non-null   object             \n",
      " 6   user_id              2126 non-null   object             \n",
      " 7   retweet_count        2126 non-null   int64              \n",
      " 8   quote_count          2126 non-null   int64              \n",
      " 9   reply_count          2126 non-null   int64              \n",
      " 10  like_count           2126 non-null   int64              \n",
      " 11  retweeted            416 non-null    object             \n",
      " 12  replied_to           1062 non-null   object             \n",
      " 13  quoted               51 non-null     object             \n",
      " 14  is_anomaly           2126 non-null   int64              \n",
      "dtypes: datetime64[ns, UTC](1), int64(5), object(9)\n",
      "memory usage: 330.3+ KB\n"
     ]
    }
   ],
   "metadata": {}
  }
 ],
 "metadata": {
  "orig_nbformat": 4,
  "language_info": {
   "name": "python",
   "version": "3.8.11",
   "mimetype": "text/x-python",
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "pygments_lexer": "ipython3",
   "nbconvert_exporter": "python",
   "file_extension": ".py"
  },
  "kernelspec": {
   "name": "python3",
   "display_name": "Python 3.8.11 64-bit ('spec-project': conda)"
  },
  "interpreter": {
   "hash": "d5626e6117a626f228c3b35b757f4e3d945537012d8c7ec5db5088829d27e251"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}